### ISSUE TITLE
Input format of test data for the neural group classification model

### ISSUE THREAD

**Issue by jakjes** [imsb-uke/epigenetic-neural-glioblastoma#1]
Hi, can you please uploade some test data that I may use for doing a validation run of the classification model? From the provided code I am not completely sure about which format I should provide my beta values in - should it be samples in rows and beta values in columns for each of the 1289 CpG sites, with or without the cg-identifiers as headers?
thanks in advance

**Comment by robinredX** [comment]
Hi Jakjes,
Pardon me for the late reply. I'll upload test data and the instructions about the format and requirements for running the code in a couple of days!
robin

**Comment by jakjes** [comment]
Hi Robin,
Thanks, I look forward to trying it out 😊
Best regards,
jakob

Jakob Schmidt Jespersen, PhD
Staff Scientist
Weischenfeldt group

University of Copenhagen
Biotech Research and Innovation Centre (BRIC) /
Finsen Laboratory, Rigshospitalet
Ole Maaløes Vej 5
Building 3, 3rd floor
2200 Copenhagen N
DENMARK

TEL +45 35 33 61 57

***@***.******@***.***>
http://www.bric.ku.dk/

[Logo for Københavns Universitet]

How we protect personal data<https://informationssikkerhed.ku.dk/english/protection-of-information-privacy/privacy-policy/>


From: Robin ***@***.***>
Reply to: imsb-uke/epigenetic-neural-glioblastoma ***@***.***>
Date: Wednesday, 12 June 2024 at 12.55
To: imsb-uke/epigenetic-neural-glioblastoma ***@***.***>
Cc: Jakob Schmidt Jespersen ***@***.***>, Author ***@***.***>
Subject: Re: [imsb-uke/epigenetic-neural-glioblastoma] Input format of test data for the neural group classification model (Issue #1)


Du får ikke ofte mails fra ***@***.*** Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>


Hi Jakjes,
Pardon me for the late reply. I'll upload test data and the instructions about the format in a couple of days!
robin

**Comment by robinredX** [comment]
Hi Jakob,

I added example data and notebook at https://github.com/imsb-uke/epigenetic-neural-glioblastoma/tree/main/code/example_neural_classification

To keep the same processing as the training data, I would recommend to also process the IDAT. The notebooks contains the steps from IDAT to prediction and displays the data formats.

Let me know if something is unclear.

**Comment by robinredX** [comment]
closing the issue for now as an example run is added. Reopen if necessary.

**Comment by jakjes** [comment]
Thanks Robin,
it looks like a good and adequate description of the required data format and pre-processing steps. I will give it a try and get back to you if I experience problems with running the classifier.
Best regards,
jakob

From: Robin ***@***.***>
Reply to: imsb-uke/epigenetic-neural-glioblastoma ***@***.***>
Date: Saturday, 15 June 2024 at 14.21
To: imsb-uke/epigenetic-neural-glioblastoma ***@***.***>
Cc: Jakob Schmidt Jespersen ***@***.***>, Author ***@***.***>
Subject: Re: [imsb-uke/epigenetic-neural-glioblastoma] Input format of test data for the neural group classification model (Issue #1)


Du får ikke ofte mails fra ***@***.*** Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>


Hi Jacob,

I added example data and notebook at https://github.com/imsb-uke/epigenetic-neural-glioblastoma/tree/main/code/example_neural_classification<https://github.com/imsb-uke/epigenetic-neural-glioblastoma/tree/main/code/example_neural_classification>

To keep the same processing as the training data, I would recommend to also process the IDAT. The notebooks contains the steps from IDAT to prediction and displays the data formats.

Let me know if something is unclear.
